### ISSUE TITLE
Release v5: what is "with characters" zip?

### ISSUE THREAD

**Issue by sunaku** [ToxicFrog/Ligaturizer#100]
Hello,

What is the difference between the two zip files in [release v5](https://github.com/ToxicFrog/Ligaturizer/releases/tag/v5)?

One of them is named "with characters" -- what does that mean?

Thanks for your consideration.

**Comment by YoRHa-A5** [comment]
@sunaku see https://github.com/ToxicFrog/Ligaturizer/issues/79#issuecomment-598995821

**Comment by ToxicFrog** [comment]
I've updated the release description to clarify this.
