### ISSUE TITLE
Owner needed

### ISSUE THREAD

**Issue by rojiani** [ToxicFrog/Ligaturizer#19]
Would like to hand the repo over, as it's not currently very high on my priority list.

@ToxicFrog, any interest?

**Comment by vikky49** [comment]
If [Toxicfrog](https://github.com/toxicfrog) takes the ownership of would be great but if not i can take it

**Comment by ToxicFrog** [comment]
I'm willing to take ownership.

**Comment by rojiani** [comment]
@ToxicFrog Thanks, I know its in good hands. To transfer it over to you, I'll need you to delete (or rename) your existing fork.

**Comment by ToxicFrog** [comment]
Done.

**Comment by ToxicFrog** [comment]
Transfer requests expire really fast, apparently -- can you re-send it?

**Comment by rojiani** [comment]
resent.
