### ISSUE TITLE
Add Source Code Pro to the repository 

### ISSUE THREAD

**Issue by pasqualedante** [ToxicFrog/Ligaturizer#24]
It would be nice to have a handy download for a ligaturized version Source Code Pro  https://github.com/adobe-fonts/source-code-pro.
Hasklig is too much Haskell centric.

**Comment by vikky49** [comment]
I have patched this repository to some of the popular fonts and will keep doing it as we update it 
You can find it here
https://github.com/vikky49/patchedFonts-Ligatures

**Comment by pasqualedante** [comment]
@vikky49 thank you
