### ISSUE TITLE
Add SourceCodePro

### ISSUE THREAD

**Issue by rofrol** [ToxicFrog/Ligaturizer#25]

**Comment by miguelsousa** [comment]
@ToxicFrog per Source Code Pro's license requirements, you cannot use the name **Source** in derivative fonts. Please correct it. Thank you.

**Comment by ToxicFrog** [comment]
@miguelsousa It's now fixed at HEAD, and renamed "LigaSrc". Let me know if you want me to filter-branch to fix it retroactively as well.

**Comment by miguelsousa** [comment]
@ToxicFrog all good now. Thanks.
