### ISSUE TITLE
Cannot patch Meslo since 8533408

### ISSUE THREAD

**Issue by agross** [ToxicFrog/Ligaturizer#29]
With commit 8533408f7a868c5cf171bd296a125e8c43224e60 patching [Meslo](https://github.com/andreberg/Meslo-Font) no longer works (the ligatures are missing):
<img width="241" alt="broken" src="https://user-images.githubusercontent.com/16245/39692739-fa13828e-51e1-11e8-9c5f-e5bbc4530847.png">

On `11b2ed7` I get this:
<img width="183" alt="2018-05-07_10-37-29" src="https://user-images.githubusercontent.com/16245/39692935-a9f0e6ba-51e2-11e8-9c83-8cc73927fa43.png">

I use [this script](https://github.com/agross/dotfiles/blob/master/iterm2/font-patcher) to patch the font and install it on macOS.

**Comment by ToxicFrog** [comment]
I tested this and it works for me on Linux, using the Meslo fonts included in the Ligaturizer repo -- can you test with those to help narrow down where the problem is? Also, what's the output from the build process?

**Comment by agross** [comment]
After running `rm -rf output-fonts/* && make` and installing the Liga Meslo LGS font manually I also see missing ligatures. I then restored `output-fonts` from GitHub and installed the one you ship in `master`, with the same results.

I then tried the following:

* `git reset --hard 8533408~` (good revision)
* removed all input fonts except `MesloLGS-Regular.ttf`
* `rm -rf output-fonts/* && make`
* installed font and checked => ✅Ligatures enabled
* <details>
  <pre>
  $ make
  fontforge -lang=py ligaturize.py  "input-fonts/MesloLGS-Regular.ttf" "output-fonts/LigaMesloLGS-Regular.ttf" 2>&1 \
  | fgrep -v 'This contextual rule applies no lookups.'
  Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
   License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
   with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
   Based on sources from 09:31 UTC 21-Mar-2018-D.
   Based on source from git with hash:
  The following table(s) in the font have been ignored by FontForge
    Ignoring 'LTSH' linear threshold table
    Ignoring 'VDMX' vertical device metrics table
    Ignoring 'hdmx' horizontal device metrics table
  The glyph named Omega is mapped to U+03A9.
  But its name indicates it should be mapped to U+2126.
  Reading ligatures from fira/FiraCode-Regular.otf
  Generated ligaturized font Liga MesloLG S Regular in output-fonts/LigaMesloLGS-Regular.ttf
  </pre>
  <details>

I then moved one commit forward and repeated:

* `git reset --hard 8533408` (bad revision)
* removed all fonts except `MesloLGS-Regular.ttf`
* `rm -rf output-fonts/* && make`
* installed font and checked => 💣Ligatures enabled
* <details>
  <pre>
  $ make
  fontforge -lang=py ligaturize.py --prefix=Liga "input-fonts/MesloLGS-Regular.ttf" "output-fonts/LigaMesloLGS-Regular.ttf" 2>&1 \
  | fgrep -v 'This contextual rule applies no lookups.'
  Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
   License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
   with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
   Based on sources from 09:31 UTC 21-Mar-2018-D.
   Based on source from git with hash:
  The following table(s) in the font have been ignored by FontForge
    Ignoring 'LTSH' linear threshold table
    Ignoring 'VDMX' vertical device metrics table
    Ignoring 'hdmx' horizontal device metrics table
  The glyph named Omega is mapped to U+03A9.
  But its name indicates it should be mapped to U+2126.
  Reading ligatures from fira/FiraCode-Regular.otf
  Generated ligaturized font Liga Meslo LG S Regular in output-fonts/LigaMesloLGS-Regular.ttf
  </pre>
  </details>

```sh
$ fontforge --version
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 09:31 UTC 21-Mar-2018-D.
 Based on source from git with hash:
fontforge 09:31 UTC 21-Mar-2018
libfontforge 20180321
```

**Comment by ToxicFrog** [comment]
Ok, I still can't reproduce this:
- checked out 81470dc27bcb9b5cf3db0bdc26188225c4d71a19
- rm output-fonts/* && make
- install output-fonts/LigaMesloLGS-*.ttf
- ligatures show up fine

I also tried downloading the latest version (1.2) of Meslo and rebuilding using that and the ligatures still show up.

**Comment by agross** [comment]
Which OS did you try this on? I just reran my script (also using Meslo 1.2). Can you compare my fonts with yours? I use VS Code to check whether ligatures work.
[liga-meslo-macos.zip](https://github.com/ToxicFrog/Ligaturizer/files/2327165/liga-meslo-macos.zip)

**Comment by ToxicFrog** [comment]
I run it on Linux, using Fontforge 20170730, and test the ligatures using Sublime Text 3 and KCharSelect.

I tried LigaMesloLGS-Regular.ttf from your zip and the ligatures showed up fine for me.

Here's my version of the font: [LigaMesloLGS-Regular.zip](https://github.com/ToxicFrog/Ligaturizer/files/2327722/LigaMesloLGS-Regular.zip) -- the ligatures in this also work fine for me.

**Comment by agross** [comment]
Thank you for providing a download. I copied your regular style to my fonts directory and suddenly VS Code having the [test file](https://github.com/tonsky/FiraCode/blob/master/showcases/showcases.txt) opened turned bold. I then removed the other variants (Bold, BoldItalic, Italic) that were left over from my last successful conversion, and the text in VS Code turned back to regular. But without ligatures!

Can you please test against VS Code on Linux and see if there are ligatures or not?

**Comment by ToxicFrog** [comment]
I'll test it and report back, but keep in mind that most programs do not cope well with the font they're using being swapped out under them; for ST3 I have to switch to another font and then back for it to properly load changes, and Konsole just crashes outright if I change the font it's currently using. So changing the font while VSC is running may not be a reliable test.

**Comment by ToxicFrog** [comment]
Ligatures work fine for me in VS Code with the following settings:

    {
        "editor.fontFamily": "'Liga Meslo LG S'",
        "editor.fontLigatures": true,
    }

**Comment by agross** [comment]
After not even a reboot provided ligatures, your VS Code settings provided the final hint 👍🏻:

```diff
{
- "editor.fontFamily": "LigaMesloLGS"
+ "editor.fontFamily": "Liga Meslo LG S"
}
```

Seems like the name changed after said commit of the OP.

**Comment by ToxicFrog** [comment]
Oh, yes, I changed the way it updates font names and metadata. It now takes the existing name embedded in the font (if present) and prefixes "Liga ". And formally, the name of that font is "Meslo LG S".

In general it's a good idea to open your OS font picker or whatever and see what it thinks the name of the font is before typing it in to something like VS Code or Sublime Text that just wants you to blindly enter the name of the font; it doesn't always match the filename. Glad you got it sorted out. :)
