### ISSUE TITLE
The command run by make (and written in the docs) doesn't work with some versions of Fontforge

### ISSUE THREAD

**Issue by NiavlysB** [ToxicFrog/Ligaturizer#30]
I'm using Fontforge 20120731.b-7.1, which is the version in the repos on Linux Mint 18.1 Serena.

Running `make` or the command `fontforge -lang=py ligaturize.py <INPUT> <OUTPUT>` launched the GUI with an error message saying _"File -lang=py does not exist."_

I had to fix the command like this: `fontforge -lang=py -script ligaturize.py <INPUT> <OUTPUT>` (prefix `ligaturize.py` with `-script`).

**Comment by NiavlysB** [comment]
Forgot to say, thanks so much for this script! Also the fact that it allows the user to skip some ligatures is great.

**Comment by NiavlysB** [comment]
Like I explained, I found the solution for my case. I just thought it might be worthwhile to mention this in the docs, and I wanted some feedback on this.

**Comment by ToxicFrog** [comment]
@tinnus pointed out in #39 that -script works with both new and old versions of fontforge, so I've added that to the makefile and documentation.
