### ISSUE TITLE
Roboto Mono Light

### ISSUE THREAD

**Issue by johnknoop** [ToxicFrog/Ligaturizer#34]
Nice! Any chance you could add Roboto Mono Light as well? I feel Roboto Mono Regular can be a bit too thick when using bright text on dark background.

**Comment by nbrombal** [comment]
I'm with you. I just ran the script on it and it seems to have worked as advertised: [LigaRobotoMono-Light.ttf.zip](https://github.com/ToxicFrog/Ligaturizer/files/2125171/LigaRobotoMono-Light.ttf.zip).

Just a note that (in Atom) I needed to set the font family as "LigaRobotoMono-Light" to show the font correctly after installing it on macOS.

**Comment by johnknoop** [comment]
Nice, thanks a lot!
