### ISSUE TITLE
Problems with macOS 10.13.5

### ISSUE THREAD

**Issue by carlca** [ToxicFrog/Ligaturizer#35]
Hello,
* I first ran `brew install fontforge` to try to avoid the dependency problem with `fontforge`.
* I've downloaded the repo, copied the standard macOS font Monaco.ttf to the input-fonts folder and ran `make`.
* I get the error:
```
  File "ligaturize.py", line 259, in <module>
    font = fontforge.open(args.input_font_path)
EnvironmentError: Open failed
```
This seems to indicate a dependency at the `python` source level. What do I have to do to get this to run?

**Comment by carlca** [comment]
I have now installed the FontForge with Python and have confirmed that I can `import fontforge` in Python 2.7.15. Unfortunately, if I then try `fontforge.open("./input-fonts/Monaco.ttf")` to replicate what the Ligaturize.py script does, I see the following...
```
Warning: Mac string is a subset of the Windows string in the 'name' table
 for the Copyright string in the English (US) language.
The glyph named gacute is mapped to U+0123.
But its name indicates it should be mapped to U+01F5.
The glyph named Scommaaccent is mapped to U+015E.
But its name indicates it should be mapped to U+0218.
The glyph named scommaaccent is mapped to U+015F.
But its name indicates it should be mapped to U+0219.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
EnvironmentError: Open failed
>>>
```
My instincts tell me that it is trying to process the command but that there is some peculiarity of the `monaco.ttf` font that is causing it to fail. 

Can anyone help?

**Comment by carlca** [comment]
I have now installed the FontForge with Python and have confirmed that I can `import fontforge` in Python 2.7.15. Unfortunately, if I then try `fontforge.open("./input-fonts/Monaco.ttf")` to replicate what the Ligaturize.py script does, I see the following...
```
Warning: Mac string is a subset of the Windows string in the 'name' table
 for the Copyright string in the English (US) language.
The glyph named gacute is mapped to U+0123.
But its name indicates it should be mapped to U+01F5.
The glyph named Scommaaccent is mapped to U+015E.
But its name indicates it should be mapped to U+0218.
The glyph named scommaaccent is mapped to U+015F.
But its name indicates it should be mapped to U+0219.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
EnvironmentError: Open failed
>>>
```
My instincts tell me that it is trying to process the command but that there is some peculiarity of the `monaco.ttf` font that is causing it to fail. 

Can anyone help?

**Comment by samjmckenzie** [comment]
I'm late, but it you're right. It's an issue with that specific file you're using. I used this one and it worked: https://transfer.sh/ie6mV/Monaco.ttf

**Comment by carlca** [comment]
Better late than never! Thanks, Sam. It works perfectly.

**Comment by S1ngS1ng** [comment]
I got a bunch of error output:
```
This contextual rule applies no lookups.
```

But seems like it works 😃

**Comment by ToxicFrog** [comment]
@S1ngS1ng That's normal; it's a side effect of the way the "ignore" rules are constructed (the ones that prevent, e.g., `------>>>>>>` from turning in a mishmash of ligatures).I've tinkered with it a bit but I don't understand Fontforge contextual alternates well enough to figure out how to get the right behaviour without generating those messages.

**Comment by S1ngS1ng** [comment]
@ToxicFrog Got it. Thanks
