### ISSUE TITLE
Script says it Generated the file, but it's not there.

### ISSUE THREAD

**Issue by frankgraave** [ToxicFrog/Ligaturizer#36]
Hi,

I have a problem with the script. The executable makefile script was hanging on this part:
`Based on source from git with hash:`  _(full output of script below)_

After this I tried a solution which was mentioned in another issue by trying this:
`fontforge -lang=py -script ligaturize.py input-fonts/RobotoMonoThin.ttf output-fonts/LigaRobotoMonoThin.ttf`

And it returned 50~100 lines with this message:
`This contextual rule applies no lookups.`

Saying at the end:
`Generated ligaturized font Liga  Roboto Mono Thin for Powerline in output-fonts/LigaRobotoMonoThin.ttf`

But the file is not there and does not seem to be generated. Any ideas?

**MacOS version:** 10.12.6
**Python version:** 2.7.15
**Fontforge:** libfontforge 20180321 (installed with brew)
**Executed in iTerm2:** Build 3.1.6

### Full output:
> /Users/frankgraave/Desktop/Ligaturizer-master/Makefile: line 8: wildcard: command not found
> /Users/frankgraave/Desktop/Ligaturizer-master/Makefile: line 9: wildcard: command not found
> /Users/frankgraave/Desktop/Ligaturizer-master/Makefile: line 11: patsubst: command not found
> /Users/frankgraave/Desktop/Ligaturizer-master/Makefile: line 12: patsubst: command not found
> /Users/frankgraave/Desktop/Ligaturizer-master/Makefile: line 14: all:: command not found
> /Users/frankgraave/Desktop/Ligaturizer-master/Makefile: line 16: output-fonts/Liga%.ttf:: No such file or directory
> /Users/frankgraave/Desktop/Ligaturizer-master/Makefile: line 17: LIGATURIZE_OPTS: command not found
> Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
>  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
>  with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
>  Based on sources from 09:29 UTC 21-Mar-2018-D.
>  Based on source from git with hash: 
>

**Comment by ToxicFrog** [comment]
What version of Make were you using, and what command did you use to run the Makefile? patsubst and wildcard might be GNU make extensions not present in whatever Make OSX has, in which case I'll have to do some research to figure out how to make it more broadly compatible. Maybe move most of the logic into a shell script?

**Comment by ToxicFrog** [comment]
The makefile is now a Python script, so this is no longer relevant.
