### ISSUE TITLE
How to remove fi and fl ligatures ?

### ISSUE THREAD

**Issue by lambdax01** [ToxicFrog/Ligaturizer#41]
Could not find entries in ligatures.py for these two.

**Comment by ToxicFrog** [comment]
Ligaturizer shouldn't add those. Are you sure they aren't present in the original font? fi and fl are very common ligatures.

**Comment by potibas** [comment]
You are right, it's probably in the original font, is there a way we could remove it?

**Comment by potibas** [comment]
Found an answer to my own question in a comment on the Meslo font repo, if anyone needs it:

https://github.com/andreberg/Meslo-Font/issues/20#issuecomment-368240071
