### ISSUE TITLE
Unable to use Ligaturizer

### ISSUE THREAD

**Issue by mustaqimM** [ToxicFrog/Ligaturizer#46]
When I try to add ligatures with `make`, I get:
```bash
fontforge -lang=py -script build.py 2>&1 \
| fgrep -v 'This contextual rule applies no lookups.' \
| fgrep -v 'Bad device table'
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 19:16 UTC  7-Sep-2018-ML-TtfDb-D.
 Based on source from git with hash: e688b8c4dc634dcc128709f84b98f2407294f3fb
Fatal Python error: _Py_InitializeCore: main interpreter already initialized

Current thread 0x00007ff8acaae480 (most recent call first):
```

I tried building `fontforge` with python2 but still get the same error.

**Comment by ToxicFrog** [comment]
Can you run other python scripts in fontforge, or is it just Ligaturizer that generates this error? If you can't run other Python scripts this is a Fontforge issue and you should report it to them; I don't know enough about it to debug issues with the fontforge/python integration.

**Comment by mustaqimM** [comment]
The nerd font patcher seems to work...

I was trying to follow @thenewvu's method:
https://github.com/be5invis/Iosevka/issues/248#issuecomment-414131620

**Comment by ToxicFrog** [comment]
I did some rummaging and the only other references I could find to this are related to (this Python 3.7 bug)[https://bugs.python.org/issue33932], which also hit Red Hat and Arch's use of fontforge. If that's the problem, though, I'd (a) expect it to go away when you use py2 and (b) expect it to hit every fontforge python script, not just ligaturizer.

What distro are you on?

**Comment by mustaqimM** [comment]
I'm on arch, I rebuilt it and now I'm getting:
```bash
Couldn't find a font file named /home/mustaqim/Ligaturizer/-lang=py
Couldn't find a font file named /home/mustaqim/Ligaturizer/-script=build.py
The following table(s) in the font have been ignored by FontForge
  Ignoring 'DSIG' digital signature table
The glyph named uni0527 is mapped to U+02DA.
  But its name indicates it should be mapped to U+0527.
The glyph named Delta is mapped to U+0394.
  But its name indicates it should be mapped to U+2206.
The glyph named Omega is mapped to U+03A9.
  But its name indicates it should be mapped to U+2126.
The glyph named mu is mapped to U+03BC.
  But its name indicates it should be mapped to U+00B5.
```
I'm on arch linux.
(I realise now that this isn't a Ligaturizer issue, please close it if you wish. If there were a IRC/matrix channel, we could discuss it there)

**Comment by mustaqimM** [comment]
I've since changed to void linux, and now it works!. I have one last query: How do I change the spacing to `100`?

**Comment by ToxicFrog** [comment]
What do you mean by "the spacing"? The em width?

**Comment by mustaqimM** [comment]
Like this:
```bash
~ 
~>  fc-list : family spacing | grep spacing
Iosevka Custom:spacing=90
```
The `kitty` terminal doesn't support fonts that don't have a spacing of `100`
