### ISSUE TITLE
Update to Latest Fira code 1.206

### ISSUE THREAD

**Issue by vikky49** [ToxicFrog/Ligaturizer#49]
Fira code has a new release https://github.com/tonsky/FiraCode/releases/tag/1.206

1.Would the  Ligaturizer repository automatically fetch the new changes when i locally build?
2. When i did git clone https://github.com/ToxicFrog/Ligaturizer --recurse-submodules
today I was getting the following error

error: Server does not allow request for unadvertised object ade27f514af43920eb4c40d354c8e0a36e9ebb12
Fetched in submodule path 'fonts/fira', but it did not contain ade27f514af43920eb4c40d354c8e0a36e9ebb12. Direct fetching of that commit failed

I can fix it if u can give me a hint .And 1.206 also has new ligatures ..I can also create a PR and update them

**Comment by vikky49** [comment]
@ToxicFrog can u let me know what to do with the checkout failure

**Comment by quinox** [comment]
I got the same submodule error, I did `cd fonts/fira` followed by `checkout master` which worked.

**Comment by ToxicFrog** [comment]
This was updated to 1.206 ages ago and I forgot to close this.
