### ISSUE TITLE
Grave accent / backtick no width with Dank Mono

### ISSUE THREAD

**Issue by bkiac** [ToxicFrog/Ligaturizer#61]
I've tried to add a few ligatures to Dank Mono which I felt, are missing.
Everything seems to work, the extra ligatures are displayed correctly, except now the grave accent character is written over other text.

This is the original Dank Mono:
![screenshot from 2019-02-23 20-30-14](https://user-images.githubusercontent.com/24522620/53291013-d93bfa80-37ac-11e9-8d3f-b1e9b5a4e5c8.png)

and with Liga Dank Mono:
![screenshot from 2019-02-23 20-30-23](https://user-images.githubusercontent.com/24522620/53291015-dc36eb00-37ac-11e9-84fa-69b04d75d286.png)

#40 might be related.

Output of `make`:
```bash
fontforge -lang=py -script build.py 2>&1 \
| fgrep -v 'This contextual rule applies no lookups.' \
| fgrep -v 'Bad device table'
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 11:21 UTC 24-Sep-2017-ML-D.
 Based on source from git with hash: 
The following table(s) in the font have been ignored by FontForge
  Ignoring 'DSIG' digital signature table
The following table(s) in the font have been ignored by FontForge
  Ignoring 'DSIG' digital signature table
Ligaturizing font DankMono-Italic.ttf (Dank Mono) as 'Liga Dank Mono'
    ...using ligatures from fonts/fira/distr/otf/FiraCode-Regular.otf
    ...saving to 'fonts/output/LigaDankMono-Italic.ttf' (Liga Dank Mono Italic)
Ligaturizing font DankMono-Regular.ttf (Dank Mono) as 'Liga Dank Mono'
    ...using ligatures from fonts/fira/distr/otf/FiraCode-Regular.otf
    ...saving to 'fonts/output/LigaDankMono-Regular.ttf' (Liga Dank Mono Regular)
```

**Comment by hatefpalizgar** [comment]
@bkiac 
## Would you please tell me how you managed to run the Py script for Dank Mono.
Since I got error each time.

thanks buddy

**Comment by bkiac** [comment]
> @bkiac
> ## Would you please tell me how you managed to run the Py script for Dank Mono.
> 
> Since I got error each time.
> 
> thanks buddy

I haven't changed anything in the script or with the font, it worked by default for me. I've used the current latest (v0.491) version.

**Comment by hatefpalizgar** [comment]
> > @bkiac
> > ## Would you please tell me how you managed to run the Py script for Dank Mono.
> > Since I got error each time.
> > thanks buddy
> 
> I haven't changed anything in the script or with the font, it worked by default for me. I've used the latest (v0.491) Dank Mono release.

Have you got trial from anywhere? or may you provide me a link to that?

**Comment by bkiac** [comment]
@hatefpalizgar 
Trial for Dank Mono? You can purchase it at https://dank.sh/.
