### ISSUE TITLE
Update Fira Code

### ISSUE THREAD

**Issue by Avi-D-coder** [ToxicFrog/Ligaturizer#69]
There are new ligatures, could you update the built fonts.

**Comment by farid-fari** [comment]
@Avi-D-coder Which ligatures specifically? Thoses mentioned in the latest release are all included in the `ligatures.py` file

**Comment by Avi-D-coder** [comment]
No new ligatures. Just the minor changes.

**Comment by farid-fari** [comment]
If it doesn't concern new ligatures, then simply doing a `git submodule update` in the repository should bring the Fira Code directory up to date and allow you to be using the latest version

**Comment by Avi-D-coder** [comment]
Yep I did that for my fork

**Comment by laurentpayot** [comment]
FiraCode [V2](https://github.com/tonsky/FiraCode/releases/tag/2) was just released with 136 new glyphs and 55 existing glyphs updated. Are there new ligatures?

**Comment by zraffer** [comment]
The new ligatures listed:
Added Coq logical and /\ and logical or \/ ligatures, U+2227 ∧ and U+2228 ∨ [#191] [#488] [#738] [#810]
Added SystemVerilog |-> |=> and <-| <=| for symmetry [#695]
Added Forces ||- ligature and U+22A2..U+22AF ⊢ ⊣ ⊤ ⊥ ⊦ ⊧ ⊨ ⊩ ⊪ ⊫ ⊬ ⊭ ⊮ ⊯ [#709]
Added fl Fl Tl ligatures, adjusted fi fj pairs [#795]
Disabled ligatures after regexp lookahead/lookbehinds (?<=< (?<=> (?<==> (?<=| (?<== (?=:= (?=!= (?== (?=== (?==> (?=> (?=>> (?=<< (?=/= (?!! (?!!. (?!= (?!== (?<!! (?<!!. (?<!= (?<!== (?<!-- [#578]
Removed ..= [#757]

**Comment by Zireael** [comment]
> If it doesn't concern new ligatures, then simply doing a `git submodule update` in the repository should bring the Fira Code directory up to date and allow you to be using the latest version

I used git `submodule update --init --recursive` if someone needs the command. If submodules are already present, doing `git submodule update --recursive --remote` should work. Might be worth adding to Readme.

**Comment by ToxicFrog** [comment]
Merged and updated to v2.
