### ISSUE TITLE
LigaSrc Pro: lowercase italic "a" is very much like lowercase italic "o"

### ISSUE THREAD

**Issue by rodrigocfd** [ToxicFrog/Ligaturizer#71]
In the LigaturizedFonts package, it seems that LigaSrc Pro font is built upon Hasklig, not Source Code Pro. The problem is that the lowercase italic "a", in Hasklig, is very much like the lowercase italic "o". In Source Code Pro, the lowercase italic "a" is clearly different.

It would be nice to have this fixed. Is there any technical impediment from building from Source Code Pro?

**Comment by ToxicFrog** [comment]
That's probably a mistake -- the current version doesn't use Hasklig for anything, or at least, it shouldn't. I'll be building a new release soon which should fix this.

**Comment by ToxicFrog** [comment]
[Release 5](https://github.com/ToxicFrog/Ligaturizer/releases/tag/v5) is now available, only a year and a half late.
