### ISSUE TITLE
Font Rename Issue

### ISSUE THREAD

**Issue by sirgru** [ToxicFrog/Ligaturizer#75]
Running the manual mode on Windows, fonts are not renamed properly. 

When double clicking the output font to install it, `Font name:` displays the source font name, in my case Source Code Pro. This happens for all source font versions except Regular, which shows the proper name.

I am also getting this error in the log:
Warning: Mac string is a subset of the Windows string in the 'name' table
  for the Family string in the English (US) language.
Warning: Mac and Windows entries in the 'name' table differ for the
  Styles (SubFamily) string in the language English (US)
  Mac String: Light
  Windows String: Regular

Files on disk are named properly. 
Putting:
    print(font.familyname)
    print(font.fontname)
    print(font.fullname)
on line 265 in ligaturize.py shows the correct, new names.

**Comment by sirgru** [comment]
Seems fixed by adding:

        replace_sfnt(font, 'Family', new_name)

on line 245

**Comment by Kamik423** [comment]
I had the same issue, thanks for the solution! This should definitely be added.
