### ISSUE TITLE
IBM Plex Mono Update

### ISSUE THREAD

**Issue by VideoPlayerCode** [ToxicFrog/Ligaturizer#79]
Found your repo through this comment:
https://github.com/IBM/plex/issues/63#issuecomment-552940293

Noticed that the "Ligaturized" release here is 9 months older than the latest Plex update:
https://github.com/IBM/plex/releases

They've done tons of little fixes, improvements and cleanups...

Any chance of an update?

I also noticed that the Ligalex Mono has a thinner default weight than IBM Plex Mono. Perhaps due to a change in a version update of the official font. Just thought I'd mention it. The IBM Plex Mono weight looks a lot better. I tried changing Ligalex Mono's weight from 400 (default) to 500 (next bigger size) but that was too fat. So the IBM Plex Mono font has a default appearance at 400 that looks like it's between the appearance of 400 and 500 of the Ligalex Mono font and is sadly impossible to reproduce in Ligalex. For that reason I'll actually use the default IBM font instead of this ligature mod...

PS: What's the difference between "LigaturizedFontsWithCharacters" and "LigaturizedFonts"? I noticed that the latter has the correct "?" symbol etc from IBM Plex whereas the "With Characters" one has modified question marks with rounded corners. Weird...

**Comment by ToxicFrog** [comment]
IBM Plex Mono has been updated to 4.0.2 in 8cfc093.

As for the weight, that depends a lot on which Plex Mono you select. "Regular" is 400, "Text" is 450, and "Medium" is 500. Ligaturizer uses a fairly crude filename-based heuristic to match up font weights, but IBM Plex Mono Regular should match up with Fira Code Mono Regular, which is also weight 400. "Text" should match up with fira's "Retina", but probably doesn't. I've created #83 to track improvements to this.

As for "LigaturizedFontsWithCharacters" vs. "LigaturizedFonts", the behaviour you describe is exactly as expected; "WithCharacters" includes not just the ligatures, but also most of the individual glyphs from Fira Code that make up the ligatures; the other only copies the ligatures. WithCharacters makes the merging of individual characters into ligatures look better, but may make those glyphs look out of place compared to the rest of the font, and how well this works in practice depends a great deal on the individual font.

**Comment by YoRHa-A5** [comment]
@ToxicFrog Thank you so much for this. After trying a lot of fonts I fell in love with the IBM Plex, but they just don't want to add ligatures, so your workaround took care of that 🙏 if only they would not have those ugly wobbly curly braces xD oh well...
