### ISSUE TITLE
Update to FiraCode 2.0 broke some ligatures

### ISSUE THREAD

**Issue by hohmannr** [ToxicFrog/Ligaturizer#82]
Hello, thanks for your work!
I saw you have just updated the code to use Fira Code 2.0, I guess this is why some of the ligatures are broken when I patch my font.

Following Ligatures are broken for me (other ones work fine; probably not a full list):

- !=
- ^=
- ~@
- ~=
- **
- *>
- |=
- :=
- =:=
- ==
- ===
- ==>
- =!=
- =>
- =>>
- =<<
- =/=
- !==

Thanks for maintaining! Raph

**Comment by ToxicFrog** [comment]
Which font are you testing? They work for me in Liga Cousine, Liga Hack, and a few others I've tried -- I haven't comprehensively gone through every font, and won't until I'm cutting a release (which won't be until I've merged a few more patches, hopefully sometime this weekend).

Note that if you're currently using the font, you will probably need to restart the program you're testing in before it will probably load all changes to the font file, and depending on your system you might need to restart the entire desktop environment.

**Comment by hohmannr** [comment]
> Note that if you're currently using the font, you will probably need to restart the program you're testing in before it will probably load all changes to the font file, and depending on your system you might need to restart the entire desktop environment.
I'm using kitty version 0.16.0 as Terminal Emulator and i3-gaps as WM. I updated the font-cache and restarted i3 as well rebooted the PC. No change unfortunately.

> Which font are you testing?
I'm using a nerd-fonts patched font called Sauce Code Pro (comes from Source Code Pro), patching the same font last week on a different machine worked fine.

> They work for me in Liga Cousine, Liga Hack, and a few others I've tried 
Tested Hack, works for me. Tested also the provided Source Code Pro Font, also worked. Probably a bug with Nerd-Fonts?

**Comment by hohmannr** [comment]
I just patched ligatures for a different font [SF-Mono](https://github.com/ZulwiyozaPutra/SF-Mono-Font/blob/master/SFMono-SemiboldItalic.otf). Ligatures work fine, but the naming seems buggy. In the patched file names there is the Liga prefix, but patching this font does not create a new name for the font family, so the font Familiy is still "SF Mono" instead of "Liga SF Mono".

When I have more time, I will try to patch this newly ligaturized font with nerd-fonts, if it works and ligatures are still present after the nerd-fonts patch, then the workaround is simple: 1st patch ligatures, then patch nerd-font-icons.

**Comment by ToxicFrog** [comment]
SF Mono naming being wrong is #15 and unrelated to this issue, I think. It's something specific to SF Mono that I still haven't figured out.

**Comment by hohmannr** [comment]
Tested it and a workaround is:
1. patch ligatures
2. then patch nerd-font-icons

Other way around does not seem to work for me!

Thanks for responding so fast. I have tested this workaround for SF Mono and Source Code Pro. Works both times. Have a great Weekend!

**Comment by jonnydee** [comment]
On my Windows 10 system "Liga Hack" doesn't support Fira Code's `<==>` ligature at least. Didn't try other fonts.

**Comment by ToxicFrog** [comment]
Does the four character ligature `<!--` work, or are four-character ligatures in general broken?

`<==>` and `<!--` both work for me in Liga Hack in Linux, FWIW.

**Comment by jonnydee** [comment]
> Does the four character ligature `<!--` work, or are four-character ligatures in general broken?
> 
> `<==>` and `<!--` both work for me in Liga Hack in Linux, FWIW.

`<!--` does work, so it seems like this is not a problem with four-character ligatures in general.
