### ISSUE TITLE
Update for Fira Code V3?

### ISSUE THREAD

**Issue by mtoohey31** [ToxicFrog/Ligaturizer#85]
Hello!
[Fira Code V3](https://github.com/tonsky/FiraCode/releases/tag/3) is out, so I'm wondering if there's an update planned for this as well.

**Comment by ToxicFrog** [comment]
This wasn't actually done, presumably because of the hope that Fira 4 would be supported, but it looks like Fira 4 has changed the way ligatures are stored (#89) so I'm reopening this -- I have a bit of time to work on it right now and I might as well update to v3.

**Comment by ToxicFrog** [comment]
Done in 640cfa3f374cfc712e2bf16a6911159b72700c55
