### ISSUE TITLE
Please use different name that ❛Source Code❜ for modified version as per OFL license

### ISSUE THREAD

**Issue by pauldhunt** [ToxicFrog/Ligaturizer#94]
Based on the terms of the Source fonts license, will you please change the name of the patched version of Source Code to NOT use the name ❛Source❜? The license allows for modification and redistribution, but retains the name Source Code for Adobe’s official version. Thanks.

**Comment by sunaku** [comment]
The patched version is already automatically renamed to "LigaSrc Pro" in build.py on line 57:

     'fonts/codeface/fonts/source-code-pro/*.ttf': 'LigaSrc Pro',

Where do you see the "Source" name still being used?

**Comment by pauldhunt** [comment]
Perfect, i was just double checking.
