### ISSUE TITLE
Wierd spacing

### ISSUE THREAD

**Issue by zUnixorn** [ToxicFrog/Ligaturizer#96]
Hi,

I tried to patch SFMono but the result looks very wierd:
![image](https://user-images.githubusercontent.com/77864446/116838216-e004fa00-abcd-11eb-83ae-4130f4ec0ccd.png)

but I know that it should be possible to patch it asthere are some other repos which provide already patched versions that don't have this problem. Does anyone know whats causing this issue?

**Comment by clsn** [comment]
Are you sure you're testing the right thing?  That's what it looks like for me when I try to open up a terminal and specify the font wrong and it winds up with a default non-monospaced font (so of course the spacing is bad.)

**Comment by ToxicFrog** [comment]
Yeah, that's not SF Mono in the screenshot -- the `l`s and `i`s are wrong. Make sure the terminal is actually loading the correct font; if you've newly created it you may need to restart the terminal and/or rebuild your fontconfig cache before it can see the new fonts.
