### ISSUE TITLE
Font Request

### ISSUE THREAD

**Issue by AhmedThahir** [ToxicFrog/Ligaturizer#97]
Hi
I don't have experience with building apps, so I would like to request someone to 'ligaturize' Montserrat.
I've attached Montserrat font files below.

[Montserrat.zip](https://github.com/ToxicFrog/Ligaturizer/files/6758119/Montserrat.zip)

**Comment by ToxicFrog** [comment]
For reference, Montserrat is a Google Font, downloadable from https://fonts.google.com/download?family=Montserrat, but the actual repo is at https://github.com/JulietaUla/Montserrat

It's released under the OFL with no Reserved Name

**Comment by ToxicFrog** [comment]
Added in c4065187a544a8fab40826fc91db1c6180a2d342
