### ISSUE TITLE
Liga Meslo has incorrect "fi" ligature

### ISSUE THREAD

**Issue by rodrigocfd** [ToxicFrog/Ligaturizer#98]
I'm using VSCode 1.58.1 (latest) on Windows 10.

Liga Meslo is rendering `fi` characters as a single ligature, as shown below:

![Screenshot](https://i.imgur.com/0Sg9fSu.png)

This makes the two `fi` chars take the space of a single char.

**Comment by ToxicFrog** [comment]
`fi` isn't one of the [ligatures copied by this tool](https://github.com/ToxicFrog/Ligaturizer/blob/master/ligatures.py) -- does plain Meslo ligaturize it if you use it with ligatures enabled?

**Comment by rodrigocfd** [comment]
Yup, it appears to be something wrong with Meslo itself.

**Comment by ThatXliner** [comment]
I'm trying to use this against MacOS's default "Menlo" which has the same problem. Perhaps they (Menlo and Meslo) are equivalent?
